// Command chromacss writes static/chroma.css: the syntax highlighting the docs'
// code blocks use, light by default and dark under prefers-color-scheme.
//
//	go run ./tools/chromacss > static/chroma.css
package main

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	formatter := chromahtml.New(chromahtml.WithClasses(true))
	var light, dark bytes.Buffer
	if err := formatter.WriteCSS(&light, styles.Get("github")); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := formatter.WriteCSS(&dark, styles.Get("github-dark")); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Each theme under its own media query rather than one on top of the other:
	// a token the light theme colours and the dark one does not would otherwise
	// keep its light colour in the dark, which is dark text on a dark block.
	fmt.Println("/* Generated by go run ./tools/chromacss. Do not edit. */")
	fmt.Println("@media (prefers-color-scheme: light) {")
	fmt.Print(strip(light.String()))
	fmt.Println("}")
	fmt.Println("@media (prefers-color-scheme: dark) {")
	fmt.Print(strip(dark.String()))
	fmt.Println("}")
}

// background matches a declaration of background colour.
var background = regexp.MustCompile(`\s*background-color:\s*#[0-9a-fA-F]+;?`)

// strip drops the background chroma paints on the block itself, which the site's
// own stylesheet owns, and keeps its text colour, which every token without a
// colour of its own inherits.
func strip(css string) string {
	var out []string
	for _, line := range strings.Split(css, "\n") {
		if strings.Contains(line, ".bg {") || strings.Contains(line, ".chroma {") {
			line = background.ReplaceAllString(line, "")
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}
